version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    env_file: 
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data/  
  web:
    build: ./csv_processing
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./csv_processing/:/usr/src/csv_processing/
      - static:/usr/src/csv_processing/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
  nginx:
    build: ./nginx_conf
    ports:
      - "7000:80"
    volumes:
      - static:/usr/src/csv_processing/static/
    depends_on:
      - web
    restart: always

volumes:
  db:
  static:
