# Generated by Django 4.2.4 on 2023-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(verbose_name='покупатель')),
                ('item', models.CharField(verbose_name='наименование товара')),
                ('total', models.IntegerField(verbose_name='cумма сделки')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество товара')),
                ('date', models.DateTimeField(verbose_name='дата и время сделки')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
            },
        ),
    ]
